name: C Check

on: [push]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make and run
      run: |
        sw_vers
        xcodebuild -version
        cd c
        make
        ./main
