# This github action workflow allows c/powl/main.c to be compiled
# and run on the 'macos-latest' platform in github actions.  Use the
# github "Actions" web interface to manually trigger the action.

name: C Check

on: workflow_dispatch

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make and run
      run: |
        sw_vers
        xcodebuild -version
        python --version
        python3 --version
        cd c/powl
        make
        ./main
